---
- hosts: demo
  become: yes
  tasks:
          - name: copy war file
            copy:
                    src: ./webapp/target/webapp.war
                    dest: /opt/apache-tomcat-8.5.55/webapps
